---
title: "진행 경과 및 계획"
description: |
  진행된 내역과 앞으로의(단기) 계획
site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# 진행 경과
BitStat는 **2021년 9월**부터 개발되 시작한 통계적 데이터 분석 툴의 프로토타이핑입니다.

현재는 데이터 입력/진단을 마무리하고, 데이터 변환 기능을 구현하고 있는 단계입니다.

<br>

* 진행 경과 표

+------------+--------------+---------------+---------------------------+
| 대분류     | 중분류       | 소분류        | 상세 기능                 |
+:===========+:=============+:==============+:==========================+
| 데이터     | 데이터 준비  | 데이터 업로드 | * CSV 파일                |
|            |              |               | * 엑셀 파일               |
|            |              |               | * R 데이터 파일           |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 준비  | 데이터 관리   | * 데이터셋 정보 편집      |
|            |              |               | * 데이터셋 삭제           |
|            |              |               | * 데이터셋 다운로드       |
|            |              |               | * 전체 다운로드           |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 진단 개요     | * 데이터 진단 개요        |
|            |              |               | * 데이터 진단 상세        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 변수별 진단   | * 개별 변수별 데이터 진단 |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 이상치        | * 이상치 진단 분석        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 진단  | 보고서 작성   | * pdf 보고서 작성         |
|            |              |               | * web 보고서 작성         |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 변환  | 변수 조작     | * 변수 이름 변경          |
|            |              |               | * 변수 형 변환            |
|            |              |               | * 변수 삭제               |
|            |              |               | * 변수 레벨 순서변경      |
|            |              |               | * 변수 레벨 변경/병합     |
|            |              |               | * 변수 변환               |
|            |              |               | * 변수 비닝               |
+------------+--------------+---------------+---------------------------+


<br>
<br>

# 단기 계획

**2021년 하반기**까지는 **기술통계와 단순선형모형을 구현**할 계획입니다.

<br>

* 진행 계획 표

+------------+--------------+---------------+---------------------------+
| 대분류     | 중분류       | 소분류        | 상세 기능                 |
+:===========+:=============+:==============+:==========================+
| 데이터     | 데이터 변환  | 데이터 정제   | * 결측치 제거/대체        |
|            |              |               | * 이상치 제거/대체        |
|            |              |               | * 중복 관측치 제거        |
+------------+--------------+---------------+---------------------------+
| 데이터     | 데이터 변환  | 데이터 분할   | * Random Simple Sampling  |
|            |              |               | * Bootstrap Sampling      |
|            |              |               | * Holdout Sampling        |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 단변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 이변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 기술통계   | EDA          | 다변량        | * 통계량                  |
|            |              |               | * 시각화                  |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 모델 적합     | * 변수선택                |
|            |              |               | * 모델 적합               |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 모델 진단     | * 모델 진단               |
+------------+--------------+---------------+---------------------------+
| 회귀분석   | 단순선형모형 | 예측          | * 예측                    |
+------------+--------------+---------------+---------------------------+

<br>
<br>

# 협업 방법
## 컨트리뷰션 아카데미
컨트리뷰션 아카데미에서 멘티들이 BitStat의 일부를 구현합니다.

### 멘티들이 기여할 수 있는 작업들
* kodlookr 패키지 구현
  + kodlookr 패키지는 dlookr 패키지의 한글 도움말 패키지로,
      + dlookr 패키지의 함수 도움말과 Vignettes(소품) 한글화
  + kodlookr 패키지는 BitStat의 도움말 리소스로 활용
      + 데이터 진단, 탐색적 데이터 분석, 데이터 변환 작업
* BitStat 메뉴/메시지의 영문화 작업 수행
  + i18n 구현을 위한 한글 메시지의 영문 번역
* BitStat 도움말을 작성
  + 기 구현 영역과 10/11월 중 구현한 기능 범위
  + 1차로 한글 도움말에 한정하여 작성
* 개발 산출물 정리 및 표준화 
  + 명명규칙에 맞게 변수 목록 표준화
  + 산출물의 오탈자 수정
* BitStat에 구현할 기능 중 심플하고 난이도 낮은 기능 개발
  + shiny 앱 개발 및 아키텍쳐 이해를 위한 경험 제공을 위한 활동으로
  + 개인의 역량을 고려하여 배분 및 진행
  
## 기타 대외 협력
현 단계에서는 고려하고 있지 않음
